apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-java-web-app
    apis.apps.tanzu.vmware.com/register-api: "true"
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: api_descriptor
    value:
      type: openssl
      location:
        baseURL: "https://github.com/sdeeg-vmware/"
        path: "tanzu-java-web-app/blob/main/api.yaml"
      owner: my_team
      system: my_system
      description: "api for java app"
  source:
    git:
      ref:
        branch: main
      url: https://github.com/sdeeg-vmware/tanzu-java-web-app.git
    #   url: https://github.com/vmware-tanzu/application-accelerator-samples.git
    # subPath: tanzu-java-web-app
